### ISSUE TITLE
Error when trying to run sarc

### ISSUE THREAD

**Issue by Nico8400** [leoetlino/sarc#1]
So I tried to extract(or list files in) a package but I got this error, 

```
Traceback (most recent call last):
  File "/usr/local/bin/sarc", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/sarc/__main__.py", line 221, in main
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/sarc/__main__.py", line 25, in sarc_list
    s = sarc.read_file_and_make_sarc(f)
  File "/usr/local/lib/python3.7/site-packages/sarc/sarc.py", line 424, in read_file_and_make_sarc
    data = wszst_yaz0.decompress(f.read())
  File "/usr/local/lib/python3.7/site-packages/wszst_yaz0/__init__.py", line 15, in decompress
    stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True).stdout
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'wszst': 'wszst'
```

The command I ran (I'm in the same folder as Weapon_Lsword_056.sbactorpack)
` sarc list Weapon_Lsword_056.sbactorpack`

**Comment by leoetlino** [comment]
Sorry, I missed your issue because I accidentally removed GitHub notifications a while ago...

sarc currently relies on wszst for fast compression and decompression. You need to install [wszst](https://szs.wiimm.de/download.html) manually on any non-Windows platform.
